version: "3"
services: 
    api:
        build: .
        tty: true
        container_name: "api"
        ports: 
            - "32799:8080"
        privileged: true
        volumes:
            - .:/go/src/charnel-horse
